package resources;
// Generated 09-mar-2023 22:01:34 by Hibernate Tools 4.3.1



/**
 * Historial generated by hbm2java
 */
public class Historial  implements java.io.Serializable {


    private Integer id;
    private String tipo;
    private int user;
    private String detalle;

   public Historial() {
   }

   public Historial(String tipo, int user, String detalle) {
      this.tipo = tipo;
      this.user = user;
      this.detalle = detalle;
   }
  
   public Integer getId() {
       return this.id;
   }
   
   public void setId(Integer id) {
       this.id = id;
   }
   public String getTipo() {
       return this.tipo;
   }
   
   public void setTipo(String tipo) {
       this.tipo = tipo;
   }
   public int getUser() {
       return this.user;
   }
   
   public void setUser(int user) {
       this.user = user;
   }
   public String getDetalle() {
       return this.detalle;
   }
   
   public void setDetalle(String detalle) {
       this.detalle = detalle;
   }




}


