package resources;

// Generated 12-mar-2023 16:24:19 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Modulos generated by hbm2java
 */
public class Modulos implements java.io.Serializable {

    private Integer id;
    private String nombre;
    private Set notases = new HashSet(0);

    public Modulos() {
    }

    public Modulos(String nombre) {
        this.nombre = nombre;
    }

    public Modulos(String nombre, Set notases) {
        this.nombre = nombre;
        this.notases = notases;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Set getNotases() {
        return this.notases;
    }

    public void setNotases(Set notases) {
        this.notases = notases;
    }

}
