package resources;
// Generated 09-mar-2023 22:01:34 by Hibernate Tools 4.3.1

/**
 * Notas generated by hbm2java
 */
public class Notascopy implements java.io.Serializable {

    private Integer idNotas;
    private Alumnos alumnos;
    private Modulos modulos;
    private Integer moduloId;
    private Integer alumnoId;
    private float notas;
    private String nombre;

    public Notascopy() {
    }

    public Notascopy(Alumnos alumnos, Modulos modulos, float notas) {
        this.alumnos = alumnos;
        this.modulos = modulos;
        this.notas = notas;
    }

    public Integer getModuloId() {
        return moduloId;
    }

    public void setModuloId(Integer moduloId) {
        this.moduloId = moduloId;
    }

    public Integer getAlumnoId() {
        return alumnoId;
    }

    public void setAlumnoId(Integer alumnoId) {
        this.alumnoId = alumnoId;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getIdNotas() {
        return this.idNotas;
    }

    public void setIdNotas(Integer idNotas) {
        this.idNotas = idNotas;
    }

    public Alumnos getAlumnos() {
        return this.alumnos;
    }

    public Integer getAlumnosId() {
        return this.alumnos.getIdAlumno();
    }

    public void setAlumnosId(Integer alumnoId) {
        this.alumnoId = alumnoId;
    }

    public void setAlumnos(String nombre) {
        this.nombre = nombre;
    }

    public Modulos getModulos() {
        return this.modulos;
    }

    public Integer getModulosId() {
        return this.modulos.getId();
    }

    public void setModulos(Modulos modulos) {
        this.modulos = modulos;
    }

    public void setModulos(Integer moduloId) {
        this.moduloId = moduloId;
    }

    public float getNotas() {
        return this.notas;
    }

    public void setNotas(float notas) {
        this.notas = notas;
    }

}
